// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdetcgwebuofvhuwdxde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZXRjZ3dlYnVvZnZodXdkeGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDU1NjAsImV4cCI6MjA3MjQ4MTU2MH0.KxL-VyFCV92qsMcNoOor80sD1KZK96MbMSdNNGBY7ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});